### ISSUE TITLE
register for VAT

### ISSUE THREAD

**Issue by winterstein** [good-loop/commercial#13]
Flat rate or normal?

**Comment by afwilli** [comment]
Also join the VAT Cash Accounting Scheme
 
https://www.gov.uk/vat-cash-accounting-scheme/eligibility

**Comment by winterstein** [comment]
@afwilli to send VAT number to DW.

**Comment by afwilli** [comment]
Darn I got VAT and corporation tax mixed up and in fact we haven't got the number yet. Sorry for the confusion, I've submitted the registration so it should be with us soon.
