### ISSUE TITLE
Software Tools: Accountancy

### ISSUE THREAD

**Issue by winterstein** [good-loop/commercial#16]
@afwilli How about we use FreeAgent?

**Comment by winterstein** [comment]
Also apply to Levima

**Comment by winterstein** [comment]
@afwilli Any thoughts on FreeAgent vs other tools?

I have experience with Xero, FreeAgent, and spreadsheets. Of those, FreeAgent would be my preference.

**Comment by afwilli** [comment]
@winterstein I have no experience with accountancy software so more than happy to go with your recommendation. 

My accountant friend suggested it might be worth paying someone to properly set it up for us as it can save headaches later down the line. How was it for you last time? How would you recommend we progress?
