### ISSUE TITLE
London visits in Feb

### ISSUE THREAD

**Issue by winterstein** [good-loop/commercial#24]
2nd Feb? Good-Loop & Francis one-to-one at 4:30pm

15th Feb? Some sort of mixer with lots of folks??

**Comment by afwilli** [comment]
Upcoming key dates / events are:

**Weds 1st** - from 9am is a session with Frank. We had a half day with him last week and he was brilliant! It'll for sure be a valuable session for you to join if possible. 
Weds 1st - in the evening is an investor mixer, again a good chance to let them get to know us more

**Thurs 2nd** - 12 - 13.30 Collider 'navigating your tech' session
4.30 - 5.30 our one-to-one with Francis 

On **Friday 3rd** I am meeting 2 of our investors, Andy (ex. Unilever, big follow-on investor) and Daniel (New to Collider this year and has good AdTech experience so might be a good one to get us in with DoubleClick) - both of which I've invited you to in case you can attend. 

**Then Thurs 15th:**
Legal session from 10, would be great to have you in that 
Brand mixer 2.30 - 5.30 - one that's essential for us both 

Other things to try and schedule whilst you're in London are 
1. A meeting with Dom to see if he might be a good ft for an advisory role
2. A meeting between us and Simon
