### ISSUE TITLE
Sales-pack for bloggers

### ISSUE THREAD

**Issue by winterstein** [good-loop/commercial#3]
For HomeGirl and The Londonist first of all

**Comment by winterstein** [comment]
a version sent to MumsNet via Jag: https://drive.google.com/drive/u/0/folders/0BzLX1qrCSys9bFBFYjVwR000Rlk

**Comment by winterstein** [comment]
Hello @afwilli,

I'd like to have the source files for these docs organised in Google Drive -- especially the latest best version of each document. That way, we know where to find them, and can all use the latest version.

NB: What software do you use for making your slide decks?

Thanks,
 - Daniel

**Comment by afwilli** [comment]
Sure I'll get them all uploaded. Its just PowerPoint.
